# KNN

## 基本思路

In [1]:
import numpy as np

In [2]:
def create_dataset():
    """
    自定义数据集
    """
    data = np.array([[1, 101], [5, 89], [108, 5], [115, 8]])
    label = np.array(['love', 'love', 'action', 'action'])
    return data, label
create_dataset()

(array([[  1, 101],
        [  5,  89],
        [108,   5],
        [115,   8]]),
 array(['love', 'love', 'action', 'action'], dtype='<U6'))

根据两点间的距离公式计算两点间的距离，选择前 $k$ 个距离最近的点，决定分类结果并返回

In [3]:
# 创建数据集 和 测试集
X, y = create_dataset()
k = 3
testset = [101, 20]

In [4]:
diff = np.tile(testset, (X.shape[0], 1)) - X
diff 

array([[100, -81],
       [ 96, -69],
       [ -7,  15],
       [-14,  12]])

In [5]:
# 测试数据与数据集的距离
dist = np.sum(diff ** 2, axis=1) ** 0.5
dist

array([128.68954892, 118.22436297,  16.55294536,  18.43908891])

In [6]:
sorted_dist_idx = dist.argsort() # 排序后的索引值

选出距离最近的 $k$ 个点的类别，通过投票的方式决定最终类别

In [7]:
class_count = dict()
for i in range(k):
    vote = y[sorted_dist_idx[i]]
    class_count[vote] = class_count.get(vote, 0) + 1
sorted_class_count = sorted(class_count.items(), key=lambda x:x[1], reverse=True)
sorted_class_count[0][0]

'action'

In [8]:
def basic_knn_classify(X, y, test, k=3):
    diff = np.tile(testset, (X.shape[0], 1)) - X
    dist = np.sum(diff ** 2, axis=1) ** 0.5
    sorted_dist_idx = dist.argsort()
    class_count = dict()
    for i in range(k):
        vote = y[sorted_dist_idx[i]]
        class_count[vote] = class_count.get(vote, 0) + 1
    sorted_class_count = sorted(class_count.items(), key=lambda x:x[1], reverse=True)
    return sorted_class_count[0][0]

basic_knn_classify(X, y, [101, 20])

'action'